FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY . .

RUN uv sync

EXPOSE 6005

CMD ["uv", "run", "uvicorn", "server:app", "--app-dir", "src", "--host", "0.0.0.0", "--port", "6005", "--timeout-keep-alive", "180"]
